### ISSUE TITLE
可以看看是什么问题吗

### ISSUE THREAD

**Issue by MrDrown32** [fsy2001/fudan-sport-automator#13]
C:\Users\zz\Desktop\main>.\main.exe -v
#40: 江湾校区夜跑
#39: 邯郸校外田径场夜跑
#38: 邯郸南区田径场夜跑
#35: 江湾田径场课外活动
#34: 邯郸校外田径场课外活动
#33: 邯郸南区田径场课外活动
#30: 江湾田径场早操
#28: 邯郸南区田径场早操
Traceback (most recent call last):
  File "main.py", line 68, in <module>
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "main.py", line 24, in main
NameError: name 'exit' is not defined
[15652] Failed to execute script 'main' due to unhandled exception!

**Comment by fsy2001** [comment]
是一个bug，但是不影响使用，已经列出了全部的刷锻选项了。再用合适的命令行参数启动刷锻即可。
