### ISSUE TITLE
本地运行出现问题

### ISSUE THREAD

**Issue by yoimiya999** [fsy2001/fudan-sport-automator#14]
Traceback (most recent call last):
  File "main.py", line 68, in <module>
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "main.py", line 24, in main
NameError: name 'exit' is not defined
[9416] Failed to execute script 'main' due to unhandled exception!
这段代码在运行之后会出现，操作也没有任何问题，是怎么回事呢

**Comment by fsy2001** [comment]
见 #13。这是由于打包成可执行文件以后exit()函数丢失的问题。该问题是在列出所有可选的刷锻列表后触发，因此不影响使用，你可以忽略这些警告。在v1.1版本中已经修复了此问题。
