### ISSUE TITLE
签名失败

### ISSUE THREAD

**Issue by lzm0036** [fsy2001/fudan-sport-automator#16]
cmd运行脚本时显示ERROR：签名失败

**Comment by yao-jingchuan** [comment]
我也出现了这个问题
具体显示是：

ERROR: 签名失败
Traceback (most recent call last):
  File "sport_api.py", line 57, in start
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 68, in <module>
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "main.py", line 57, in main
  File "sport_api.py", line 60, in start
NameError: name 'exit' is not defined
[8224] Failed to execute script 'main' due to unhandled exception!

**Comment by caomulan** [comment]
我也是，求帮助！
ERROR: 签名失败
Traceback (most recent call last):
  File "sport_api.py", line 57, in start
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 68, in <module>
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "main.py", line 57, in main
  File "sport_api.py", line 60, in start
NameError: name 'exit' is not defined
[3648] Failed to execute script 'main' due to unhandled exception!

**Comment by fsy2001** [comment]
脚本寄咯 更新之前老实去跑步吧🏃

**Comment by Elsiiii** [comment]
什么时候能更新哇大佬！！！爱信等！！！（实在不想跑……）

**Comment by jxycyza** [comment]
同签名失败，大佬求求了

**Comment by jxycyza** [comment]
我可以付费咨询的，https://www.wjx.cn/vm/YhBx4l6.aspx请填写下联系方式

**Comment by fsy2001** [comment]
脚本用不了是因为小程序更新的问题，不是运行方式错误。在研究出这个小程序的签名方式之前是不能自动刷锻的。

**Comment by habacat** [comment]
小程序APP源码弄了一份在这里，供大家研究研究
https://i.fudan.site/7pjhj4BkiY
signature地址：https://api.mdc.movecloud.cn/api/oss-signature
![image](https://github.com/fsy2001/fudan-sport-automator/assets/41714213/2f4f5260-4d8e-4ad4-a728-43ebb9459269)

我自己体育课上完了无锻可刷，看看诸位大佬们的功力了

**Comment by fsy2001** [comment]
原来只是个MD5啊，那好说

**Comment by fsy2001** [comment]
感谢 @habacat 弄的源码😋

**Comment by solitudeindark** [comment]
ERROR: Token错误 应该是没搞错的，不知道为什么

**Comment by Leonard-Zhan** [comment]
> ERROR: Token错误 应该是没搞错的，不知道为什么

已经更新了token了，可以再用fiddler爬一次

**Comment by jxycyza** [comment]
PS D:\桌面\fudan-sport-automator-main (1)\fudan-sport-automator-main> python main.py --route 33
Traceback (most recent call last):
  File "D:\桌面\fudan-sport-automator-main (1)\fudan-sport-automator-main\main.py", line 68, in <module>
    asyncio.run(main())
  File "C:\Users\11056\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\11056\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "D:\桌面\fudan-sport-automator-main (1)\fudan-sport-automator-main\main.py", line 57, in main
    await automator.start()
  File "D:\桌面\fudan-sport-automator-main (1)\fudan-sport-automator-main\sport_api.py", line 56, in start
    params = sign_param(params)
  File "D:\桌面\fudan-sport-automator-main (1)\fudan-sport-automator-main\sport_api.py", line 100, in sign_param
    vals = ",".join(arr)
TypeError: sequence item 1: expected str instance, float found

**Comment by fsy2001** [comment]
> PS D:\桌面\fudan-sport-automator-main (1)\fudan-sport-automator-main> python main.py --route 33 Traceback (most recent call last): File "D:\桌面\fudan-sport-automator-main (1)\fudan-sport-automator-main\main.py", line 68, in asyncio.run(main()) File "C:\Users\11056\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run return loop.run_until_complete(main) File "C:\Users\11056\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete return future.result() File "D:\桌面\fudan-sport-automator-main (1)\fudan-sport-automator-main\main.py", line 57, in main await automator.start() File "D:\桌面\fudan-sport-automator-main (1)\fudan-sport-automator-main\sport_api.py", line 56, in start params = sign_param(params) File "D:\桌面\fudan-sport-automator-main (1)\fudan-sport-automator-main\sport_api.py", line 100, in sign_param vals = ",".join(arr) TypeError: sequence item 1: expected str instance, float found

是个bug，可以下载v2.0.2再试试

另外，不同的问题建议单独开issue

**Comment by 1623295825** [comment]
Traceback (most recent call last):
  File "aiohttp/connector.py", line 980, in _wrap_create_connection
  File "asyncio/base_events.py", line 1103, in create_connection
  File "asyncio/base_events.py", line 1133, in _create_connection_transport
  File "asyncio/sslproto.py", line 534, in data_received
  File "asyncio/sslproto.py", line 188, in feed_ssldata
  File "ssl.py", line 975, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 68, in <module>
  File "asyncio/runners.py", line 44, in run
  File "asyncio/base_events.py", line 649, in run_until_complete
  File "main.py", line 20, in main
  File "sport_api.py", line 28, in get_routes
  File "aiohttp/client.py", line 1189, in __aenter__
  File "aiohttp/client.py", line 536, in _request
  File "aiohttp/connector.py", line 540, in connect
  File "aiohttp/connector.py", line 901, in _create_connection
  File "aiohttp/connector.py", line 1206, in _create_direct_connection
  File "aiohttp/connector.py", line 1175, in _create_direct_connection
  File "aiohttp/connector.py", line 982, in _wrap_create_connection
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host sport.fudan.edu.cn:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')]
[11853] Failed to execute script 'main' due to unhandled exception!
