### ISSUE TITLE
使用Mac运行时SSL证书报错

### ISSUE THREAD

**Issue by MrMole0910** [fsy2001/fudan-sport-automator#6]
<img width="682" alt="Screen Shot 2023-05-22 at 6 34 32 PM" src="https://github.com/fsy2001/fudan-sport-automator/assets/134281213/3fedb1d6-7cb0-41f0-934b-a5b0f9f6ae5c">
如图，恳请解答，感谢。

**Comment by fsy2001** [comment]
请检查是否启用了代理软件，如果启用了请关闭后重试

**Comment by Kage-233** [comment]
我也出现了这个问题，检查了应该没有启用代理软件，文科生完全不懂啊，大佬orz
Traceback (most recent call last):
  File "aiohttp/connector.py", line 980, in _wrap_create_connection
  File "asyncio/base_events.py", line 1103, in create_connection
  File "asyncio/base_events.py", line 1133, in _create_connection_transport
  File "asyncio/sslproto.py", line 534, in data_received
  File "asyncio/sslproto.py", line 188, in feed_ssldata
  File "ssl.py", line 975, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 68, in <module>
  File "asyncio/runners.py", line 44, in run
  File "asyncio/base_events.py", line 649, in run_until_complete
  File "main.py", line 40, in main
  File "sport_api.py", line 24, in get_routes
  File "aiohttp/client.py", line 1189, in __aenter__
  File "aiohttp/client.py", line 536, in _request
  File "aiohttp/connector.py", line 540, in connect
  File "aiohttp/connector.py", line 901, in _create_connection
  File "aiohttp/connector.py", line 1206, in _create_direct_connection
  File "aiohttp/connector.py", line 1175, in _create_direct_connection
  File "aiohttp/connector.py", line 982, in _wrap_create_connection
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host sport.fudan.edu.cn:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')]
[1745] Failed to execute script 'main' due to unhandled exception!


<img width="651" alt="截屏2023-09-18 下午7 14 14" src="https://github.com/fsy2001/fudan-sport-automator/assets/145343804/fe7fe41a-dbcc-4914-a428-f3ba7c3dcaa5">
