### ISSUE TITLE
指定的网络不可再用

### ISSUE THREAD

**Issue by yxxx027** [fsy2001/fudan-sport-automator#8]
UPDATE: 操作成功 (921.2041001159446m / 1197.3150918890408m)
UPDATE: 操作成功 (924.615967153411m / 1197.3150918890408m)
UPDATE: 操作成功 (928.0278341908775m / 1197.3150918890408m)
UPDATE: 操作成功 (931.4397012283439m / 1197.3150918890408m)
UPDATE: 操作成功 (934.8515682658103m / 1197.3150918890408m)
UPDATE: 操作成功 (938.2634353032768m / 1197.3150918890408m)
UPDATE: 操作成功 (941.6753023407432m / 1197.3150918890408m)
Traceback (most recent call last):
  File "main.py", line 68, in <module>
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "main.py", line 61, in main
  File "sport_api.py", line 69, in update
  File "aiohttp\client.py", line 1189, in __aenter__
  File "aiohttp\client.py", line 560, in _request
  File "aiohttp\client_reqrep.py", line 899, in start
  File "aiohttp\streams.py", line 616, in read
aiohttp.client_exceptions.ClientOSError: [WinError 64] 指定的网络名不再可用。
[10672] Failed to execute script 'main' due to unhandled exception!
出现这个错误要怎么解决

**Comment by fsy2001** [comment]
右键单击计算机，进入“管理”。
展开服务和应用程序，点击“服务”，检查“computer、Browser、server、workstation”是否启动，如果没有启动，点击“启动”。
